const UPDATE_CONTENT = "UPDATE_CONTENT";
const UPDATE_COMMENT = "UPDATE_COMMENT";
const DETAIL_CONTENT = "DETAIL_CONTENT";
const DETAIL_COMMENT = "DETAIL_COMMENT";

export { UPDATE_COMMENT, UPDATE_CONTENT, DETAIL_CONTENT, DETAIL_COMMENT };
